# Generated by Django 4.0.3 on 2022-03-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=50)),
                ('time', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('threadhold', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_pest', models.BooleanField()),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pots.pest')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pots.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pots.user'),
        ),
        migrations.CreateModel(
            name='Imgae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgURL', models.CharField(max_length=250)),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pots.pest')),
            ],
        ),
    ]
